<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Request;
use Throwable;

use App\Common\Facade\Console;
use App\Models\Factory\BaseResponse;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    public function render($request, Throwable $e)
    {
        Console::writeLine(
            $e->getMessage() . " at \n" .
            $e->getFile() . ":" . $e->getLine() .
            "\n\n"
            . $e->getTraceAsString()
            . "\n\n\n\n"
        );

        if(str_contains(Request::url(), '/api/')){
            return BaseResponse::error(
                $e->getMessage(),
                $e->getCode() === 0 ? 500 : $e->getCode(),
                $e->getFile() . ":" . $e->getLine()
            );
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
